### PR TITLE
Feature/bootcamp googlemaps

### PR DESCRIPTION
**Pull request by Edouard-6**

### CODE REVIEW

**Review by NervzZ — COMMENTED** [review]
Please remove comments from tutorial copy paste parts and TODO later.
Next time please don't forget to run Code > Format Code so we all have the same and it should fix the line return differences.
Otherwise looks good to me.

**Review by NervzZ — COMMENTED** [review]
.

**Review by NervzZ — APPROVED** [review]
Please remove comments from tutorial copy paste parts and TODO later.
Next time please don't forget to run Code > Format Code so we all have the same and it should fix the line return differences.
Otherwise looks good to me.

**Comment by tepoorte** [comment]
Looks good to me!

**Review by tepoorte — APPROVED** [review]
Looks good to me!

**Pull request merged**
